In [35]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


from sklearn import preprocessing #we can convert text to numbers 
from sklearn.model_selection import train_test_split  # for train test splitting of data
from sklearn.naive_bayes import GaussianNB # for Naive Bayes therom
from sklearn.metrics import accuracy_score  # for Model accuracy
from sklearn.metrics import confusion_matrix # for records classification
from sklearn.naive_bayes import *

In [18]:
df = pd.read_csv("E:\\python\\Day24\\train.csv")
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [94]:
dftrain = df.drop(["Name","Ticket"],axis=1)


In [20]:
dftrain.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [95]:
le = preprocessing.LabelEncoder()

In [96]:
le.fit(dftrain["Sex"])

LabelEncoder()

In [97]:
print(le.classes_)

['female' 'male']


In [98]:
dftrain["Sex"] = le.transform(dftrain["Sex"])
dftrain["Sex"]

0      1
1      0
2      0
3      0
4      1
      ..
884    1
885    0
886    0
887    1
888    1
Name: Sex, Length: 889, dtype: int32

In [99]:
le.fit(dftrain["Embarked"])
print(le.classes_)
dftrain["Embarked"] = le.transform(dftrain["Embarked"])
dftrain["Embarked"]

['C' 'Q' 'S']


0      2
1      0
2      2
3      2
4      2
      ..
884    2
885    2
886    2
887    0
888    1
Name: Embarked, Length: 889, dtype: int32

In [100]:
dftrain = dftrain.drop(["PassengerId","Cabin"],axis = 1)
dftrain

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
884         0       2    1  27.0      0      0  13.0000         2
885         1       1    0  19.0      0      0  30.0000         2
886         0       3    0  45.0      1      2  23.4500         2
887         1       1    1  26.0      0      0  30.0000         0
888         0       3    1  32.0      0      0   7.7500         1

[889 rows x 8 columns]

In [47]:
y = dftrain.Survived # dependent variable
y

0      0
1      1
2      1
3      1
4      0
      ..
884    0
885    1
886    0
887    1
888    0
Name: Survived, Length: 889, dtype: int64

In [101]:
X =dftrain.drop(["Survived"],axis = 1) # Independent variable
X

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         3    1  22.0      1      0   7.2500         2
1         1    0  38.0      1      0  71.2833         0
2         3    0  26.0      0      0   7.9250         2
3         1    0  35.0      1      0  53.1000         2
4         3    1  35.0      0      0   8.0500         2
..      ...  ...   ...    ...    ...      ...       ...
884       2    1  27.0      0      0  13.0000         2
885       1    0  19.0      0      0  30.0000         2
886       3    0  45.0      1      2  23.4500         2
887       1    1  26.0      0      0  30.0000         0
888       3    1  32.0      0      0   7.7500         1

[889 rows x 7 columns]

In [102]:
y.count()

889

In [50]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [51]:
X_train.head()

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
350       1    1  45.0      0      0  35.0000         2
124       3    1  12.0      1      0  11.2417         0
577       3    0  45.0      1      0  14.4583         0
422       3    0  28.0      1      1  14.4000         2
118       3    0   2.0      4      2  31.2750         2

In [52]:
X_train.count()

Pclass      622
Sex         622
Age         622
SibSp       622
Parch       622
Fare        622
Embarked    622
dtype: int64

In [53]:
clf = BernoulliNB() # method to clissify data in NaiveBayes therom

In [55]:
y_pred = clf.fit(X_train,y_train).predict(X_test) #prediction--- based on training data we can predict the out put of test data 

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1], dtype=int64)

In [57]:
accuracy_score(y_test,y_pred,normalize=True) #how much percentage it accuratly classified

0.7715355805243446

Based on training dataset 77.71 percentage test data is accurately classified

In [58]:
confusion_matrix(y_test,y_pred)

array([[131,  26],
       [ 35,  75]], dtype=int64)

In [113]:
def nb(dv):
    clf = BernoulliNB()
    for i in dv:
        print (f"The dependent variable is {i} ")
        y = dftrain[i]
        X = dftrain.drop([i],axis = 1)
        X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
        y_pred = clf.fit(X_train,y_train).predict(X_test)
        print("\n\nAccuracy Score\n", accuracy_score(y_test,y_pred,normalize=True))
        print("------------------------------------------------------------")
        print("\n\nConfusion Matrix\n",confusion_matrix(y_test,y_pred))
    

In [114]:
idv = ['Pclass', 'Sex', 'SibSp', 'Parch', 'Embarked']
nb(idv)

The dependent variable is Pclass 


Accuracy Score
 0.5917602996254682
------------------------------------------------------------


Confusion Matrix
 [[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]
The dependent variable is Sex 


Accuracy Score
 0.7453183520599251
------------------------------------------------------------


Confusion Matrix
 [[ 49  49]
 [ 19 150]]
The dependent variable is SibSp 


Accuracy Score
 0.6891385767790262
------------------------------------------------------------


Confusion Matrix
 [[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]
The dependent variable is Parch 


Accuracy Score
 0.7153558052434457
------------------------------------------------------------


Confusion Matrix
 [[182  16   0   0   0]
 [ 31   9   0   0   0]
 [ 24   3   0   0   0]
 [  1   0   0   0   0]
 [  1   0   0   0 