In [2]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [218]:
ran = np.random.rand(3,3,3)
ran

array([[[0.84594551, 0.92630623, 0.94018721],
        [0.63629925, 0.7579483 , 0.29874718],
        [0.09510908, 0.10067596, 0.10848537]],

       [[0.35000413, 0.76903509, 0.18604665],
        [0.86213382, 0.27403   , 0.10802592],
        [0.36259554, 0.37815001, 0.71892649]],

       [[0.57803672, 0.96216965, 0.65234517],
        [0.11004877, 0.76322256, 0.08937842],
        [0.60315131, 0.76243322, 0.016893  ]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [121]:
di = np.diag(1+np.arange(4), k=-1)
print(di)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[0 1]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [61]:
x = np.zeros((8,8), dtype=int)
x[::2,1::2] = 1
x[1::2,::2] = 1

print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [84]:
ranarray1 = np.random.rand(5,5)
print("Before Normalize:\n",ranarray1,"\n")
amax, amin = ranarray1.max(), ranarray1.min()
ranarray1 = (ranarray1-amin)/(amax-amin)
print("After Normalize:\n",ranarray1,"\n")

Before Normalize:
 [[0.10802931 0.52215473 0.41788243 0.25980684 0.45579932]
 [0.09797694 0.56030125 0.0195762  0.9258285  0.37177309]
 [0.4288501  0.07711951 0.28358326 0.73374686 0.32868392]
 [0.54685298 0.14658119 0.20097941 0.72179695 0.32043832]
 [0.31003512 0.62818765 0.6215432  0.01656369 0.34325778]] 

After Normalize:
 [[0.10059295 0.55604378 0.44136619 0.26751629 0.48306679]
 [0.08953745 0.59799692 0.00331314 1.         0.39065561]
 [0.45342832 0.06659867 0.29366535 0.78875061 0.3432666 ]
 [0.58320666 0.1429919  0.2028185  0.77560823 0.33419817]
 [0.32275684 0.67265768 0.66535019 0.         0.35929478]] 



# 5.  How to find common values between two arrays?

In [124]:
x = np.array([1,2,3])
y = np.array([4,1,3])

print("The common values are:",np.intersect1d(x,y)) 



The common values are: [1 3]


# 6.How to get the dates of yesterday, today and tomorrow?

In [129]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-28
Today:  2020-07-29
Tomorrow:  2020-07-30


# 7. Consider two random array A and B, check if they are equal

In [179]:
x = np.random.rand(3,3,3)
y = np.random.rand(3,3,3)
print(np.allclose(x,y))

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [194]:
x = np.random.rand(10)
print("Array Befor:\n",x)
x[x.argmax()]=0
 
print("Array After:\n",x)

Array Befor:
 [0.23007804 0.08689479 0.28259653 0.66884943 0.55191399 0.14487214
 0.43150967 0.22465624 0.14592811 0.17285339]
Array After:
 [0.23007804 0.08689479 0.28259653 0.         0.55191399 0.14487214
 0.43150967 0.22465624 0.14592811 0.17285339]


# 9. How to print all the values of an array?

In [203]:
x = np.arange(10)
print(x)



[0 1 2 3 4 5 6 7 8 9]


# 10.Subtract the mean of each row of a matrix

In [211]:
a = np.arange(2,11).reshape(3,3)
b= a - a.mean(axis=1, keepdims=True)
print(b)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [212]:
a = np.random.randint(1,10,10)
print("Given vector:", a)
b = np.random.randint(a)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:", b)
print("Result:",a)

Given vector: [9 5 2 4 2 3 4 1 9 1]
Indexing vector: [0 0 0 0 0 1 1 1 2 5]
Result: [10  6  3  4  2  4  4  1  9  1]


# 12.How to get the diagonal of a dot product?

In [114]:
a = np.array([[1,2,],[2,3]])
b = np.array([[3,2,],[4,3]])
c = np.dot(a,b)
print(c)
print("The diagonal of dot product is:",np.diag(c))


[[11  8]
 [18 13]]
The diagonal of dot product is: [11 13]


# 13.How to find the most frequent value in an array?

In [213]:
a=np.random.randint(2,15,10)
print(a)
print(np.bincount(a).argmax())

[10 12  8 14  8  6  8 13 12  5]
8


# 14.How to get the n largest values of an array

In [220]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 5
print (x[np.argsort(x)[-n:]])



Original array:
[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


# 15.How to create a record array from a regular array?

In [221]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
print(r[1])
print(r.b)

(2, 'dd', 2.)
['a' 'dd' 'xyz' '12']
